### ISSUE TITLE
erro ao iniciar um projeto

### ISSUE THREAD

**Issue by cristianormoraes** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#127]
Olá boa tarde! estou tentando utilizar o framework, em um primeiro inicio me deparei com este erro:

Message=Not found a valid configuration section with name 'Secrets'.

Não consegui achar instruções para qual configuração está faltando no meu projeto.

**Comment by guilhermeluizsp** [comment]
Você precisa adicionar uma seção chamada "Secrets" dentro do arquivo de configurações (appsettings.json). Se você olhar o [exemplo que está no repositório](https://github.com/Avanade/Liquid-Application-Framework/tree/be28f796798fe4f9648b96e5cf9b484dd63846fa/samples/Liquid.Sample.CarRegistry), perceberá que essa seção se encontra lá. Basta copiar o template:

https://github.com/Avanade/Liquid-Application-Framework/blob/be28f796798fe4f9648b96e5cf9b484dd63846fa/samples/Liquid.Sample.CarRegistry/appsettings.json#L76-L80

Isso percente ao sistema de configurações secretas que o Framework providencia. Para que seja ativado, é necessário definir a chave `Enabled` como `true`, atribuir `K8S_SECRETS` para a chave `Module` e definir um valor para a chave `Name`. Depois disso, crie um arquivo na raiz do projeto (onde o appsettings.json se encontra) na pasta: `secrets/appsettings.[Name].k8ssecrets.json` onde `[Name]` é o mesmo valor que você definiu na chave `Name`.

Se não quiser usar, basta definir a chave `Enable` como `false`.

Creio que a idéia desse sistema é funcionar da mesma maneira que o [Secret Manager](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets) do ASP.NET Core. 

@bruno-brant Can you provide us insights from this feature? Should this be a mandatory configuration?

**Comment by bruno-brant** [comment]
en: No, I don't think so, I think this kind of feature should be optional.
pt: Não, acho que não. Acredito que esse tipo de funcionalidade deveria ser opcional. 

Let's register yet another feature request to make this optional.

**Comment by bruno-brant** [comment]
Hey @cristianormoraes, if it still fails, please let us know, otherwise I'll close the issue.

**Comment by cristianormoraes** [comment]
Ok @bruno-brant , funcionando! obrigado
