### ISSUE TITLE
Erro ao retornar dados do cosmosdb

### ISSUE THREAD

**Issue by cristianormoraes** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#136]
Saudaçõe srs.

Estou tentando retornar dados do CosmosDb e a principio não encontrei muita informação sobre a utilização, configurei o appsettings.json com:

"CosmosDB": {
    "Endpoint": "https://localhost:8081",
    "AuthKey": "xxx",
    "DatabaseId": "api1",
    "CollectionName": "liquidsample"
  }

![cosmos](https://user-images.githubusercontent.com/758854/70537922-012ffb00-1b40-11ea-8dc4-1a5228f0da59.png)

No Startup.cs coloquei:

WorkBench.UseRepository<CosmosDB>();

E no meu service tentei buscar dados:

var records = await Repository.GetAsync<Cliente>(x => true);

Porém peguei um erro:

![erro](https://user-images.githubusercontent.com/758854/70537813-d645a700-1b3f-11ea-97df-10818268aae4.png)

O que posso estar fazendo errado?

**Comment by thiagones** [comment]
Olá, Cristiano!
Qual era o problema?

**Comment by cristianormoraes** [comment]
@thiagones Não havia chamado o app.UseWorkBench(); no startup.cs 

:(

Aproveitando, existe algum macete para fazer um post de json em um metodo de api? Estou postando e o model não pega os valores das propriedades... estou usando o postman....

**Comment by thiagones** [comment]
Da uma olhada se o case das propriedades que você está enviando no json está correto.
Se a propriedade é se chama "Xpto" (X maiúsculo), dependendo da configuração do serializer não é possível passar "xpto" (x minúsculo) no json

**Comment by cristianormoraes** [comment]
Sim, testei isso mas infelizmente não está dando bind..

Existe alguma configuração de algum intermediador na requisição do POST ?

**Comment by cristianormoraes** [comment]
Outra dificuldade que estou tendo e nao achei nada a respeito na documentação, é como é feita a geração do arquivo

System.IO.FileNotFoundException: 'Could not find file 'C:\Source\Workbench\Backend\LiquidSample\bin\Debug\netcoreapp2.2\AppTeste.xml'.'

acredito que seja para o Swagger? poderia me explicar @thiagones
