### ISSUE TITLE
LightWorker roda em loop?

### ISSUE THREAD

**Issue by cristianormoraes** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#151]
_pt:_ Eu estou tentando ler uma fila no servicebus, criei um ClienteWorker do tipo LightWorker, consegui enviar uma mensagem para o servicebus, porem não consigo fazer a leitura, o LightWorker fica rodando em loop puxando a fila do servicebus ou ele roda assíncrono ?

Depois que eu iniciei o microserviço eu vi que ele chamou o metodo do ClienteWorker somente uma única vez, é necessário alguma configuração extra para fazer o serviço ficar sempre ativo?

_en_: I am trying to read a queue on servicebus, I created a LightWorker ClientWorker, I was able to send a message to servicebus, but I can't read it, does LightWorker loop around pulling the servicebus queue or does it run asynchronously?

After I started the microservice I saw that it called the ClientWorker method only once, does it need some extra configuration to make the service always active?

**Comment by bruno-brant** [comment]
_pt:_ @cristianormoraes o Liquid se registra no ServiceBus como um listener, ou seja, o ServiceBus que chama o Liquid e não há a necessidade de polling ("loop").

_en:_ @cristianormoraes Liquid registers with ServiceBus as a listener, i.e., its the ServiceBus that calls Liquid, therefore there's no need to perform any polling ("loop").
