### ISSUE TITLE
Azure AD

### ISSUE THREAD

**Issue by cristianormoraes** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#157]
Consigo utilizar o Azure AD no Liquid ? 

Como deveria ficar a configuração do mesmo?

**Comment by guilhermeluizsp** [comment]
Atualmente o Liquid não possui integração com o AD nativamente, você precisa fazer a integração manualmente.

**Comment by bruno-brant** [comment]
Creio que isso seria uma feature mínima para o software, lembrando que estamos falando especificamente de autorização via OAuth2.

**Comment by bruno-brant** [comment]
Closing this issue as it seems the question was answered.
