### ISSUE TITLE
ILightTelemetry doesn't have a method to track exceptions

### ISSUE THREAD

**Issue by bruno-brant** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#159]
Tracking exceptions is a must in telemetry/observability.

Although such method is available at `LightTelemetry` class, it isn't at `ILightTelemetry`.

**Comment by guilhermeluizsp** [comment]
This is kind of unrelated to this issue but the Framework also violates the LSP in a lot of places by casting the interface to a `LightTelemetry`

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAWS/MessageBuses/AwsSqsSns.cs#L102

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAWS/MessageBuses/AwsSqsSns.cs#L110

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAWS/MessageBuses/AwsSqsSns.cs#L161

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAWS/MessageBuses/AwsSqsSns.cs#L169

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAzure/Databases/CosmosDB.cs#L324

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAzure/Hubs/EventHub.cs#L61

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAzure/Hubs/EventHub.cs#L107

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAzure/MessageBuses/ServiceBus.cs#L63

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAzure/MessageBuses/ServiceBus.cs#L99

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAzure/MessageBuses/ServiceBus.cs#L117

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAzure/MessageBuses/ServiceBus.cs#L158

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnAzure/MessageBuses/ServiceBus.cs#L203

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnGoogle/MessageBuses/PubSub.cs#L99

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnGoogle/MessageBuses/PubSub.cs#L111

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnPre/MessageBuses/MicrosoftMessageQueuing.cs#L76

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.OnPre/MessageBuses/MicrosoftMessageQueuing.cs#L103

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.Repository/LightRepository.cs#L503

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.Runtime/Telemetry/LightMetric.cs#L15

https://github.com/Avanade/Liquid-Application-Framework/blob/d3c19c13217053a7fa2ac0072fe9330b626e3a76/src/Liquid.Runtime/Telemetry/LightTelemetryMiddleware.cs#L102

**Comment by bruno-brant** [comment]
OMG...
