### ISSUE TITLE
InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.

### ISSUE THREAD

**Issue by cristianormoraes** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#164]
Estou tentando utilizar autorização no controller e estou pegando este erro:

**InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.**

Eu não entendi bem como funciona a configuração do Auth mas tentei configura dessa forma:

**"Auth": {
    "Authority": "https://login.microsoftonline.com",
    "Audiencies": "xxxx.onmicrosoft.com",
    "Credentials": false
  }**

**Comment by guilhermeluizsp** [comment]
Mostre-nos o código do Startup do seu projeto, por favor. Se possível, envie também o StackTrace da exception.

**Comment by bruno-brant** [comment]
I'm closing this from lack of information. We can reopen the issue if more information is provided.
