### ISSUE TITLE
LightWorker rethrow exceptions

### ISSUE THREAD

**Issue by bruno-brant** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#206]
LightWorker throws exceptions received from the worker, resetting their stack. 

https://github.com/Avanade/Liquid-Application-Framework/blob/d437ed2e596cec3d5547373e8b6a456d94a3e7ff/src/Liquid.Activation/Worker/LightWorker.cs#L173

This is problematic for debugging issues in production code.

**Comment by bruno-brant** [comment]
Also realized that it won't throw or rethrow exceptions when the method is parameterless.

**Comment by guilhermeluizsp** [comment]
Should we consider this issue a duplicate of #23?

**Comment by bruno-brant** [comment]
> Should we consider this issue a duplicate of #23?

Yep.

**Comment by bruno-brant** [comment]
Duplicate of #23
