### ISSUE TITLE
Justify the use of the method ValidateInterfaces

### ISSUE THREAD

**Issue by guilhermeluizsp** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#22]
Inside the WorkBench class, we have a method called ValidateInterfaces:

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.Base/WorkBench.cs#L100-L105

It checks if the type T implements the interface name you passed as a parameter. If it doesn't, it throws an ArgumentException.

Besides that, there are other methods to set up Workbench services (such as repository or message bus):

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.Base/WorkBench.cs#L64

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.Base/WorkBench.cs#L70

These methods also accept a generic type parameter which will be instantiated at runtime (```new T()```), but before instantiating them, they call ```ValidateInterfaces``` and pass their generic constraint as a parameter. Take the ```UseRepository``` as an example:

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.Base/WorkBench.cs#L64-L68

Notice how it calls ```ValidateInterfaces<T>(nameof(ILightRepository));```?

Is it necessary though? Since the methods already have generic constraints, it's impossible to violate them (not even via Reflection).

We just can't call ```WorkBench.UseRepository<string>()``` for example, because string does not meet the generic constraints, so the call to ```ValidateInterfaces``` seems to have no real use.

**Comment by bruno-brant** [comment]
I agree that the call is unnecessary. Since those methods should only be called on application startup, the impact of the check is minimal, so this is an improvement and not a bug.

Also easy to validate a PR in this case, since we should just be removing the call to `ValidateInterfaces`.

Also, we must check if the method is used in some other place - if that's no the case, we should also remove it altogether.
