### ISSUE TITLE
Stop using async void methods

### ISSUE THREAD

**Issue by guilhermeluizsp** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#24]
While we can make a method that returns void asynchronous (i.e async void), we should avoid doing it and leave it to exception handlers only.

Async void methods cannot be awaited and exceptions cannot be caught using try-catch blocks, which will make them bubble up to the synchronization context or be raised as unobserved exceptions.

The natural return value of asynchronous methods are Task or ValueTask (and custom awaitables, of course).

If a class implements an interface which has a method that returns void and its implementation is asynchronous, we should consider making the interface method asynchronous as well or rethink the design of the implementation.

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.OnAWS/Storages/S3.cs#L51-L54

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.OnAzure/Storages/AzureBlob.cs#L99-L107

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.OnGoogle/Databases/GoogleFireStore.cs#L73-L81

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.OnGoogle/Databases/GoogleFireStore.cs#L87-L103

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.OnGoogle/Databases/GoogleFireStore.cs#L590-L603

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.OnGoogle/Storages/GoogleStorage.cs#L46-L49

**Comment by bruno-brant** [comment]
This is problematic. There are numerous issues concerning async methods that we must clean up as soon as possible.

This one, at least, should be rather simple to solve.

@guilhermeluizsp feel free to provide a PR with the necessary adjustments.
