### ISSUE TITLE
LightDomain has duplicate properties of type ICriticHandler

### ISSUE THREAD

**Issue by guilhermeluizsp** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#53]
The LightDomain class has both a private and a public property of the type ICriticHandler:

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/Base/Domain/LightDomain.cs#L20-L21

I assume the private was intended to be used as a backing field for the public one.
Analyzing the code, I believe we can keep only the public version

**Comment by bruno-brant** [comment]
This is ugly. I'll mark it as an enhancement since it brings no faulty behavior, but I think we should fix it as soon as possible.
