### ISSUE TITLE
LightDomain is not thread safe

### ISSUE THREAD

**Issue by guilhermeluizsp** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#56]
`LightDomain` is a base class intended to be used to process the business logic of a specific context. It has a set of methods such as _AddBusinessError_, _AddNotFound_ and _Response_ that reinforce this argument.

When you want to return a problematic result (a validation failure or a business logic error), you should call these methods and they will show up in the ending result.

Those business methods only direct the logic to its ICriticHandler:

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/Base/Domain/LightDomain.cs#L30-L72

If we take a closer look, the instance of the ICriticHandler is used across the entire class, and as it doesn't have any locking mechanism, we can attest that it would cause issues if we used the same instance of the `LightDomain` do call multiple methods, as the state would conflict with one another.

Take this service as an example:

```csharp
//LightService is a LightDomain
public class MyService : LightService
{
    public DomainResponse Method1()
    {
        AddNotFound("'Not found' from method 1");
        return Response("method1");
    }

    public DomainResponse Method2()
    {
        AddBusinessError("'Business Error' from method 2");
        return Response("method2");
    }
}
```

It has two methods. They both add issues to the final result.

If we reused the service instance to make calls to Method1 and Method2, they would share the state and (as stated earlier) return a conflicting response:

```csharp
var myService = new MyService();
var response1 = myService.Method1();
//response2 contains "'Not found' from method 1"
var response2 = myService.Method2();
```

This is even worse if we start considering concurrent scenarios.

One could argue that the intended use of LightDomain is to create an instance per method but if that's the case, I'd like to hear the benefits of this approach (as I don't see that creating multiple instances would be healthy to the performance of the application and the cleanliness of the code).

**Comment by bruno-brant** [comment]
Is LightDomain singleton? I thought every request would be handled by a different domain service.

**Comment by guilhermeluizsp** [comment]
> Is LightDomain singleton? I thought every request would be handled by a different domain service.

I think you're right. I was thinking about reusing those methods, but as you said, they are (currently) intended to be called once per request.

I'm closing this issues since it's the desired behavior.
