### ISSUE TITLE
WorkBench.AddToCache method won't correctly throw ArgumentException

### ISSUE THREAD

**Issue by guilhermeluizsp** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#62]
The order of the parameters for the ArgumentException are: message, parameter name
This method, however, inverts the order

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Base/WorkBench.cs#L50-L56

It should also use the nameof operator

**Comment by bruno-brant** [comment]
I consider this to be a bug because the exceptions messages in any log will be wrong.
