### ISSUE TITLE
WorkBench.ValidateInterfaces method won't correctly throw ArgumentException

### ISSUE THREAD

**Issue by guilhermeluizsp** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#63]
The order of the parameters for the ArgumentException are: message, parameter name
This method, however, inverts the order

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Base/WorkBench.cs#L100-L105

It should also use the nameof operator

**Comment by bruno-brant** [comment]
I consider it a bug since it'll result in mistakes in error messages.
