### ISSUE TITLE
LightAPI is too much coupled with Bearer Authentication

### ISSUE THREAD

**Issue by guilhermeluizsp** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#65]
The constructor of both `LightAPI` and `AbstractAPIWrapper` (which `LightAPI` inherits from) accepts a parameter called `token` described as "token authentication"

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L24-L30

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/APIWrapper.cs#L28-L34

This variable is used within `LightAPI` to authenticate the requests using Bearer Authentication.

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L73-L74

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L117-L118

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L197-L199

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L234-L236

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L273-L275

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L321-L323

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L373-L375

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L511-L513

https://github.com/Avanade/Liquid-Application-Framework/blob/93f7874f2ead13d3602cc39fc1e9355206217f57/src/Liquid.Domain/API/LightAPI.cs#L578-L580

Though this authentication scheme is extremely popular nowdays, we shouldn't force our mechanism to make HTTP requests (`LightAPI`) to only work that way, as (obviously) we wouldn't be able to work with APIs that don't follow this standard.

**Comment by bruno-brant** [comment]
Although I believe that this might be done by design, I can clearly see that this coupling is problematic - microservices built with Liquid will certainly need to call external services that do not use Bearer tokens.

**Comment by bruno-brant** [comment]
I think the reason for this is the same as I mentioned on #103 - LightApi is designed to be used only to allow communication between Liquid services.

**Comment by bruno-brant** [comment]
LightApi is a poor wrapper over HttpClient. As stated on #150, we should simply retire it in favor of a better solution such as RestSharp.
